language: php
sudo: required
php:
  - '7.2'
services:
  - mysql
cache:
  directories:
    - node_modules
    - ~/.npm
    - vendor
git:
  depth: 3
before_install:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE `testing_laravel`;'
before_script:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader --no-interaction
  - npm install
script:
  - php artisan migrate
  - php artisan test
notifications:
  email:
    recipients:
      - johannitaarango2@gmail.com
      - larangogon1@uniminuto.edu.co
    on_success: always
    on_failure: always
